FROM node:15.11.0-alpine3.13
#FROM node:15.11.0
# Ставим недостающие пакеты
RUN apk add --update python3 autoconf automake libtool make tiff jpeg zlib zlib-dev pkgconf nasm file gcc musl-dev g++
# Устанавливаем рабочую папку
WORKDIR /usr/src/app
# Копируем файлы настроек рабочего окружения проекта
COPY ./package*.json .
COPY ./yarn.lock .
# Устанавливаем рабочую среду
RUN yarn install
# Копируем файлы настроек проекта
#COPY ./nuxt.config.js .


# Стартуем проект
#ENTRYPOINT ["yarn", "run", "dev"]


