version: '3.9'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: nosmag-frontend
    restart: unless-stopped
    command: yarn run start
    stdin_open: true
    tty: true

    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=${NUXT_HOST}
      - NUXT_PORT=3000
      - API_PROTOCOL=${AXIOS_API_PROTOCOL}
      - API_PREFIX=${AXIOS_API_PREFIX}
      - API_HOST=${AXIOS_API_HOST}
      - API_PORT=${AXIOS_API_PORT}
#      - NODE_ENV:production
      - NODE_ENV:development
    networks:
      - nosmag-network

  nginx:
    image: nginx:stable-alpine
    container_name: nosmag-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - nosmag-network

#volumes:
#  mongodb_api:
#  mongodb_auth:

networks:
  nosmag-network:
    driver: bridge

