version: '3'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: nosmag-frontend
    restart: unless-stopped
    command: yarn run start
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - API_PROTOCOL=https
      - API_PREFIX=/api
      - API_HOST=nosmag.ru
      - API_PORT=443
      - NODE_ENV:production
    networks:
      - nosmag-network

  nginx:
    image: nginx:stable-alpine
    container_name: nosmag-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - nosmag-network

#volumes:
#  mongodb_api:
#  mongodb_auth:

networks:
  nosmag-network:
    driver: bridge

