version: '3.3'
# version: '3.9'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    command: yarn run dev
    stdin_open: true
    tty: false
    environment:
      - BROWSER_BASE_URL=${BROWSER_BASE_URL_LOCAL}
      - NODE_ENV:development

    volumes:
      - ./frontend/src:/usr/src/app/src
      - .././images:/usr/src/app/src/static/images

  nginx:
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/dev:/etc/nginx

# networks:
#   nosmag-network:
#     external: true
#     name: host
    # driver: host
