version: '3.3'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: nosmag-frontend
    restart: unless-stopped
    command: yarn run start
    stdin_open: true
    tty: true

    ports:
      - "3000:3000"

    environment:
      - NUXT_HOST=${NUXT_HOST}
      - NUXT_PORT=3000
      - API_PREFIX=${AXIOS_API_PREFIX}
      - BROWSER_BASE_URL=${BROWSER_BASE_URL}
      - SERVER_BASE_URL=${SERVER_BASE_URL}
      - NODE_ENV:production
      # - NODE_ENV:development
    volumes:
      # - test_volume:/usr/src/app/src/static/images
      # - test_vol:/usr/src/app/static/imag:ro
      # - ./images:/usr/src/app/src/static/images
      - .././images:/usr/src/app/static/images
      # - /home/store/Projects/NosMag/NosMag-app/images:/usr/src/app/src/static/images

    networks:
      - nosmag-network

  nginx:
    image: nginx:stable-alpine
    container_name: nosmag-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - nosmag-network

# volumes:
#   # test_volume:
#   #   external: true
#   test_vol:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/store/Projects/NosMag/NosMag-app/images

networks:
  nosmag-network:
    driver: bridge

