version: '3.3'
# version: '3.9'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: nosmag-frontend
    restart: unless-stopped
    command: yarn run start

    ports:
      - "3000:3000"

    environment:
      - NUXT_HOST=${NUXT_HOST}
      - NUXT_PORT=3000
      - API_PREFIX=${AXIOS_API_PREFIX}
      - BROWSER_BASE_URL=${BROWSER_BASE_URL}
      - SERVER_BASE_URL=${SERVER_BASE_URL}
      - NODE_ENV:production
    volumes:
      - .././images:/usr/src/app/static/images

    networks:
      - nosmag-network

  nginx:
    image: nginx:stable-alpine
    container_name: nosmag-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/prod:/etc/nginx
      # - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - nosmag-network

networks:
  nosmag-network:
    driver: bridge

